# -*- coding: utf-8 -*-
"""Protect_Pet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19SUPLh_UpvTiXo70j9ABg_0MEpvUnlqr
"""

import random
from datetime import datetime, time

def gerar_protocolo():
    return f"PT-{random.randint(1000,9999)}-{random.randint(1000,9999)}"

def horario_com_analista():
    return True

def confirmar_satisfacao():
    print("\nProtectPetBot: Esta informação foi satisfatória? (sim/não)")
    resp = input().lower()
    if resp == "sim":
        mais_duvidas = input("ProtectPetBot: Deseja tirar mais alguma dúvida? (sim/não): ").lower()
        if mais_duvidas == "não":
            print("ProtectPetBot: Agradecemos seu contato com a ProtectPet. Até logo! 🐾")
            exit()
        else:
            print("Retornando ao menu principal...\n")
    else:
        print("ProtectPetBot: Lamentamos! Um atendente será acionado se necessário (horário comercial).\n")

def confirmar_satisfacao_duvidas():
    print("\nProtectPetBot: Esta informação foi satisfatória? (sim/não)")
    resp = input().lower()
    if resp == "sim":
        mais_duvidas = input("ProtectPetBot: Deseja tirar mais alguma dúvida? (sim/não): ").lower()
        if mais_duvidas == "sim":
          print("ProtectPetBot: Agradecemos seu contato com a ProtectPet. Até logo! 🐾")
          duvidas()
    else:
        print("Retornando ao menu de Dúvidas...\n")



def cadastrar_cliente():
    print("\nProtectPetBot: Vamos iniciar o cadastro do responsável.")
    nome_cliente = input("Nome completo: ")
    cpf = input("CPF (apenas números): ")
    rg = input("RG (apenas números e/ou letras): ")
    endereco = input("Endereço completo (CEP, Rua, Bairro, Estado): ")
    data_de_nascimento = input("Data de nascimento (DD/MM/AAAA): ")
    email = input("E-mail: ")
    telefone = input("Telefone: ")


    contatos_emergencia = []
    for i in range(1):
        add_contato = input(f"Deseja adicionar pessoa de contato {i+1}? (sim/não): ").lower()
        if add_contato == "sim":
            nome_contato = input("Nome do contato: ")
            tel_contato = input("Telefone do contato: ")
            email_contato = input("E-mail do contato: ")
            contatos_emergencia.append({
                "nome": nome_contato,
                "telefone": tel_contato,
                "email": email_contato
            })

    return {
        "nome": nome_cliente,
        "endereco": endereco,
        "email": email,
        "telefone": telefone,
        "contatos_emergencia": contatos_emergencia
    }

def cadastrar_pet():
    print("\nProtectPetBot: Agora, vamos cadastrar seu pet.")
    nome = input("Nome do pet: ")
    tipo = input("Tipo de pet (cachorro, gato, etc.): ")
    raca = input("Raça do pet: ")
    sexo = input("Sexo do pet (M para Macho/F para Fêmea): ")
    porte = input("Porte (pequeno, médio ou grande): ")
    nascimento = input("Data de nascimento do pet (DD/MM/AAAA): ")

    return {
        "nome": nome,
        "tipo": tipo,
        "raca": raca,
        "sexo": sexo,
        "porte": porte,
        "nascimento": nascimento
    }

def selecao_produto():
    print("\nProtectPetBot: Antes de seguir para o processo de pagamento, vamos selecionar os dados da coleira para o seu pet.")
    cor = input("Cor da coleira: ")
    print("\nProtectPetBot: Estamos com dois modelos de coleiras disponíveis para seu pet:")
    print("Tradicional (pescoço) – R$200,00")
    print("Peitoral (visando conforto) – R$250,00")
    print("Ambas são resistentes, seguras e ideais para o dia a dia.")
    tipo = input("Agora por favor, nos informe qual o tipo de coleira deseja.")


    return {
        "cor": cor,
        "tipo": tipo
    }

def fluxo_compra():
    cliente = cadastrar_cliente()
    pet = cadastrar_pet()
    selecao_produto()

    print("\nProtectPetBot: Aqui estão as funcionalidades da nossa coleira:")
    print("- Rastreamento GPS em tempo real 🌍")
    print("- Resistente à água 💦")
    print("- Suporte 24h via aplicativo 📱")
    print("- Localização por chat caso o app esteja fora do ar 🧭")
    print("- Bateria recarregavel com duração de carga de até 170 horas! 🔋")

    print("\nProtectPetBot: Um boleto será enviado para o e-mail cadastrado no valor do Produto selecionado. Ressaltamos que o pagamento leva até dois dias para compensação bancária.")
    metodo_entrega = input("Deseja receber em outro e-mail ou no WhatsApp? (Digite 'email', 'whatsapp' ou 'não'): ").lower()

    if metodo_entrega == "email":
        novo_email = input("Informe o novo e-mail: ")
        print(f"ProtectPetBot: O boleto será enviado para {novo_email}.")
    elif metodo_entrega == "whatsapp":
        zap = input("Informe o número com DDD: ")
        print(f"ProtectPetBot: O boleto será enviado via WhatsApp para {zap}.")
    else:
        print(f"ProtectPetBot: O boleto será enviado para o e-mail cadastrado: {cliente['email']}.")

    print("\n⚠️ Atenção:")
    print("Título do e-mail: [ProtectPet] Pagamento de sua Coleira GPS")
    print("Descrição: Este é o único canal oficial de cobrança da ProtectPet. Fique atento a golpes!")

    print("\nApós a confirmação do pagamento:")
    print("- A produção leva até 3 dias úteis.")
    print("- A entrega leva até 5 dias úteis (variando conforme o endereço).")
    print("- Você receberá por e-mail o código de rastreio do pedido.")

    protocolo = gerar_protocolo()
    print(f"\n✅ Protocolo de atendimento: {protocolo}")
    print("-" * 50)

    confirmar_satisfacao()

def abrir_ticket(tipo, detalhes):
    ticket_id = gerar_protocolo()
    print(f"\n🎫 Ticket criado para '{tipo}': {ticket_id}")
    print(f"Detalhes: {detalhes}")
    print("-" * 50)

def suporte():
    print("\nProtectPetBot: Qual tipo de suporte você precisa?")
    print("1 - Manutenção do Produto")
    print("2 - Troca da Coleira")
    print("3 - Informações em tempo real do pet")

    suporte_opcao = input("Digite o número da opção: ")

    if suporte_opcao == "1":
        problema = input("\nDescreva o problema ou digite 'quebra' se for esse o caso: ").lower()

        if "quebra" in problema:
            print("ProtectPetBot: 💡 Procedimentos sugeridos:")
            print("1. Verifique se a coleira está bem presa e sem partes soltas.")
            print("2. Reinicie o dispositivo segurando o botão por 5 segundos.")

            resposta = input("A coleira voltou a funcionar? (sim/não): ").lower()
            if resposta == "não":
                print("ProtectPetBot: Vamos solicitar a troca ou a visita técnica.")
                visita = input("Deseja agendar uma visita técnica? (sim/não): ").lower()
                if visita == "sim":
                    if horario_com_analista():
                        print("ProtectPetBot: Transferindo para um analista disponível para finalizar o atendimento e agendar a visita... 🔧")
                else:
                    abrir_ticket("Solicitação de Troca", "Produto não resolveu após tentativa de manutenção.")
            else:
                abrir_ticket("Manutenção Realizada", "Problema resolvido pelo cliente.")
        else:
            abrir_ticket("Manutenção do Produto", problema)

    elif suporte_opcao == "2":
        motivo = input("Motivo da troca: ")
        abrir_ticket("Troca de Coleira", f"Motivo: {motivo}"), print("Dentro de algumas horas, um de nossos analistas entrará em contato para confirmar as informações, bem como identificar se a troca do produto é devida")

    elif suporte_opcao == "3":
        print("ProtectPetBot: Localizando seu pet...")
        print("Endereço: Rua da cachorrada, 78 - Santo Amaro")
        print("Latitude: -23.5505, Longitude: -46.6333")
        abrir_ticket("Informações em Tempo Real", "Localização enviada ao cliente.")
    else:
        print("ProtectPetBot: Opção inválida. Tente novamente.")
        confirmar_satisfacao()

def duvidas():
    print("\nProtectPetBot: Qual a sua dúvida?")
    print("1 - Qual o horário de funcionamento do SAC?")
    print("2 - Quais são as características da coleira?")
    print("3 - A coleira funciona offline para rastreamento?")
    print("4 - A coleira precisa de chip ou internet para funcionar o GPS?")

    opcao = input("Digite o número da dúvida: ")

    if opcao == "1":
        print("ProtectPetBot: Nosso SAC funciona de segunda a sexta, das 8h às 18h. 🕗")
    elif opcao == "2":
        print("ProtectPetBot: Nossa coleira é de fácil modelagem com revestimento em couro da cor desejada, pingente com nome do pet, compacta, confortável e com bateria que dura até 170 horas! 💡")
    elif opcao == "3":
        print("ProtectPetBot: Sim! A coleira funciona de forma offline para rastreamento graças à conectividade com a nuvem que envia os dados aos nossos sistemas e ao tutor. 📡")
    elif opcao == "4":
        print("ProtectPetBot: Não! O GPS da coleira utiliza um protocolo leve (MQTT) otimizado para pequenos dispositivos, sem necessidade de chip ou internet para funcionar. 🚫📶")
    else:
        print("ProtectPetBot: Opção inválida. Por favor, tente novamente.")

    confirmar_satisfacao_duvidas()

def chatbot():
    print("ProtectPetBot: 🐾 Olá! Bem-vindo ao atendimento da ProtectPet.\n")

    while True:
        print("Menu de Atendimento:")
        print("1 - Comprar Produto")
        print("2 - Suporte")
        print("3 - Dúvidas")
        print("4 - Sair")
        opcao = input("Digite o número da opção desejada: ")

        if opcao == "1":
            fluxo_compra()
        elif opcao == "2":
            suporte()
        elif opcao == "3":
            duvidas()
        elif opcao == "4":
            print("ProtectPetBot: Obrigado por conversar com a ProtectPet, em caso de Duvidas, é só chamar. Até logo! 🐶")
            break
        else:
            print("ProtectPetBot: Opção inválida. Por favor, tente novamente.\n")

chatbot()